language: node_js
node_js:
  - "5"

services:
  - mysql

before_script:
  - mysql -e "create database IF NOT EXISTS database_dev;" -uroot
  - mysql -e "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'gEVNL8Y9YU';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON database_dev. * TO 'dev'@'localhost';" -uroot
